# Generated by Django 5.0 on 2023-12-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
