# Generated by Django 5.0 on 2023-12-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
