# Generated by Django 5.0 on 2023-12-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='progress',
            field=models.CharField(choices=[('P', 'pending'), ('I', 'in progress..'), ('C', 'completed')], default='P', max_length=1),
        ),
    ]
