# Generated by Django 5.0 on 2023-12-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todolist_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='progress',
            field=models.CharField(choices=[('pending', 'pending'), ('in progress..', 'in progress'), ('completed', 'completed')], default='pending', max_length=30),
        ),
    ]
