# Generated by Django 5.0 on 2023-12-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todolist_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='progress',
        ),
    ]
