# Generated by Django 5.0 on 2023-12-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_todolist_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('workers', models.ManyToManyField(to='todo.worker')),
            ],
        ),
    ]
