# Generated by Django 5.0 on 2023-12-28 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_worker_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductWorkersThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.product')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.worker')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='workers',
            field=models.ManyToManyField(through='todo.ProductWorkersThrough', to='todo.worker'),
        ),
    ]
