# Generated by Django 5.0 on 2023-12-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_product_productworkersthrough_product_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productworkersthrough',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
