# Generated by Django 5.0 on 2023-12-28 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_productworkersthrough_in_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoWorkerThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=10)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todolist')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.worker')),
            ],
        ),
        migrations.AddField(
            model_name='todolist',
            name='workers',
            field=models.ManyToManyField(through='todo.TodoWorkerThrough', to='todo.worker'),
        ),
    ]
