# Generated by Django 5.0 on 2024-01-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_alter_todolist_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-date']},
        ),
    ]
